BEGIN;

DROP TABLE IF EXISTS ALOCACOES_SUPERAVIT;
DROP TABLE IF EXISTS SNAPSHOTS_MENSAIS;
DROP TABLE IF EXISTS ORCAMENTOS_MENSAIS;
DROP TABLE IF EXISTS TRANSACOES_RECORRENTES;
DROP TABLE IF EXISTS PREFERENCIAS_USUARIO;

ALTER TABLE CATEGORIAS
  DROP COLUMN IF EXISTS ativo;

ALTER TABLE USUARIOS
  DROP COLUMN IF EXISTS onboarding_completed_at,
  DROP COLUMN IF EXISTS last_transaction_date,
  DROP COLUMN IF EXISTS planning_completed_at;

COMMIT;
