ALTER TABLE CONTAS_BANCARIAS
ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

UPDATE CONTAS_BANCARIAS
SET ativo = TRUE,
    created_at = COALESCE(created_at, NOW()),
    updated_at = COALESCE(updated_at, NOW());

UPDATE USUARIOS
SET onboarding_completed_at = NOW()
WHERE onboarding_completed_at IS NULL;
