ALTER TABLE categorias
  ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE categorias
SET is_default = TRUE
WHERE id <= 8;

ALTER TABLE moedas
  ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE moedas
  ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE moedas
SET is_default = TRUE
WHERE codigo IN ('USD', 'BRL', 'EUR', 'GBP');
